name: CI-CD

on:
  push: 
    branches: ['main']
  workflow_dispatch: 
jobs: 
  ci: 
    runs-on: ubuntu-latest
    steps:
      - name: Obtem codigo do projeto
        uses: actions/checkout@v4

      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Contrucao e Envio da Imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: | 
            tavarescruz/fake-shop:latest
            tavarescruz/fake-shop:v${{ github.run_number }}

  cd: 
    runs-on: ubuntu-latest
    needs: [ci]
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Autenticar na AWS com Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Configurar o kubectl
        run: aws eks update-kubeconfig --name eks-developer

      - name: List files in the k8s directory
        run: |
          echo "Listing files in the ./k8s directory:"
          ls -l

      - name: Aplicar os manifestos (deploy) no Kubernetes
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
              ./k8s/deployment.yaml
          images: |
              tavarescruz/fake-shop:v${{ github.run_number }}
